# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160114_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expires',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='fingerprint',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
