# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160124_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='image',
            field=models.TextField(),
        ),
    ]
