# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import api.models
import uuid
import datetime
from django.utils.timezone import utc


def fix_cert(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    certificate = apps.get_model("api", "Certificate")
    for cert in certificate.objects.all():
        # many new fields are updated
        cert.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160208_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='fingerprint',
            field=models.CharField(default=datetime.datetime(2016, 1, 28, 5, 52, 47, 586393, tzinfo=utc), editable=False, max_length=96),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 1, 28, 5, 52, 47, 586393, tzinfo=utc), max_length=253, unique=True, validators=[api.models.validate_label]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='san',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='common_name',
            field=models.TextField(editable=False, unique=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer',
            field=models.TextField(default=datetime.datetime(2016, 1, 28, 5, 52, 47, 586393, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='starts',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 28, 5, 52, 47, 586393, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject',
            field=models.TextField(default=datetime.datetime(2016, 1, 28, 5, 52, 47, 586393, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(fix_cert),
    ]
